services:
  newt:
    image: fosrl/newt
    container_name: newt
    env_file: .env
    restart: unless-stopped
    networks:
      - newt_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  newt_network:
    driver: bridge
